### ISSUE TITLE
Starting print nanny monitoring alerts do not work and trigger a weird state

### ISSUE THREAD

**Issue by dzervas** [bitsy-ai/octoprint-nanny-webapp#45]
I'm on a dev setup currently! - base commit: e22cc19
When I send a command "Start Print Nanny Monitoring" through the Web UI (NOT octoprint), I get the following django messages trace:
```
django             | Internal Server Error: /api/commands/79/
django             | Traceback (most recent call last):
django             |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 339, in thread_handler
django             |     raise exc_info[1]
django             |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
django             |     response = await get_response(request)
django             |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 231, in _get_response_async
django             |     response = await wrapped_callback(request, *callback_args, **callback_kwargs)
django             |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 304, in __call__
django             |     ret = await asyncio.wait_for(future, timeout=None)
django             |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
django             |     return await fut
django             |   File "/usr/local/lib/python3.8/site-packages/asgiref/current_thread_executor.py", line 23, in run
django             |     result = self.fn(*self.args, **self.kwargs)
django             |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 343, in thread_handler
django             |     return func(*args, **kwargs)
django             |   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
django             |     return func(*args, **kwds)
django             |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
django             |     return view_func(*args, **kwargs)
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
django             |     return self.dispatch(request, *args, **kwargs)
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
django             |     response = self.handle_exception(exc)
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
django             |     self.raise_uncaught_exception(exc)
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
django             |     raise exc
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
django             |     response = handler(request, *args, **kwargs)
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 82, in partial_update
django             |     return self.update(request, *args, **kwargs)
django             |   File "/app/print_nanny_webapp/remote_control/api/views.py", line 124, in update
django             |     alert_settings_attr = alert_settings.command_to_attr(command.command)
django             |   File "/app/print_nanny_webapp/alerts/models.py", line 192, in command_to_attr
django             |     return getattr(self, snake_cased)
django             | AttributeError: 'RemoteControlCommandAlertSettings' object has no attribute 'monitoring_start'
django             | ERROR 2021-02-08 15:38:04,699 log 12405 140443452901120 Internal Server Error: /api/commands/79/
django             | Traceback (most recent call last):
django             |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 339, in thread_handler
django             |     raise exc_info[1]
django             |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
django             |     response = await get_response(request)
django             |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 231, in _get_response_async
django             |     response = await wrapped_callback(request, *callback_args, **callback_kwargs)
django             |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 304, in __call__
django             |     ret = await asyncio.wait_for(future, timeout=None)
django             |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
django             |     return await fut
django             |   File "/usr/local/lib/python3.8/site-packages/asgiref/current_thread_executor.py", line 23, in run
django             |     result = self.fn(*self.args, **self.kwargs)
django             |   File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 343, in thread_handler
django             |     return func(*args, **kwargs)
django             |   File "/usr/local/lib/python3.8/contextlib.py", line 75, in inner
django             |     return func(*args, **kwds)
django             |   File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
django             |     return view_func(*args, **kwargs)
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
django             |     return self.dispatch(request, *args, **kwargs)
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
django             |     response = self.handle_exception(exc)
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
django             |     self.raise_uncaught_exception(exc)
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
django             |     raise exc
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
django             |     response = handler(request, *args, **kwargs)
django             |   File "/usr/local/lib/python3.8/site-packages/rest_framework/mixins.py", line 82, in partial_update
django             |     return self.update(request, *args, **kwargs)
django             |   File "/app/print_nanny_webapp/remote_control/api/views.py", line 124, in update
django             |     alert_settings_attr = alert_settings.command_to_attr(command.command)
django             |   File "/app/print_nanny_webapp/alerts/models.py", line 192, in command_to_attr
django             |     return getattr(self, snake_cased)
django             | AttributeError: 'RemoteControlCommandAlertSettings' object has no attribute 'monitoring_start'
```

in addition (maybe a different issue?) when this error rises, the octoprint instance HAS to be restarted for any consecutive alerts to arrive!

Maybe it would reconnect if I waited long enough? (I'm testing alerts currently so I can't wait)

**Comment by leigh-johnson** [comment]
I couldn't reproduce this against v0.5.0-rc2 - looks like this bug was fixed in passing. Let me know if you still see this issue. Thank you!
